version: "3"

services:

  server:
    image: spring

    # if you need to create an image for convert sentence to AMR choose between the following
    # build: server/AMRLIB
    # build: server/
    build: server/spring

    # select the following comand base on which image you used
    # command: python AMRBART/fine-tune/predict_AMR.py $PORT
    command: python spring/converterToAMR_server.py $PORT
    # command: python AMRLIB/02_generate_amrs.py $PORT

    ports:
      - $PORT:$PORT

    volumes:
      - $HOME:$HOME

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [$CUDA_VISIBLE_DEVICES]
              capabilities: [gpu]

  client:
    image: project_client
    build: client/

    command:
      ./settings.sh $PORT

    network_mode: host

    depends_on:
      - server
    
    volumes:
      - $HOME:$HOME

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [$CUDA_VISIBLE_DEVICES]
              capabilities: [gpu]